### ISSUE TITLE
here's an ammend that will make it work with sd-next/vladmatic

### ISSUE THREAD

**Issue by Captain-Bacon** [aria1th/webui-model-uploader#8]
Hi there,

I had some issues when I tried to download some models because the directory structure is slightly different in SD-Next.

I hope you don't mind the suggestions, but here's a way around resolving the path issue:

`@lru_cache(maxsize=1)
def get_controlnet_dir() -> str:
    from modules.shared import opts
    cnet_models_path = opts.data.get('control_net_modules_path', None)
    if not cnet_models_path:
        if os.path.exists(os.path.join(basepath, 'extensions-builtin')) and os.path.exists(os.path.join(basepath, 'extensions')):
            cnet_extension_path = os.path.join(basepath, 'extensions-builtin', 'sd-webui-controlnet')
        else:
            cnet_extension_path = os.path.join(basepath, 'extensions', 'sd-webui-controlnet')
        if not os.path.exists(cnet_extension_path):
            print(f"Could not find controlnet extension at {cnet_extension_path}")
            return ""
        cnet_models_path = os.path.join(cnet_extension_path, 'models')
    return cnet_models_path`

All the code does is check to see if there's a directory called _extensions-builtin_  as well as the regular extensions folder, and if there is then it amends the path name to that.  SD-Next comes pre-built with some extensions, so has this slightly different structure, and this is a way to solve that issue.

I haven't checked out any of the other functions, but hopefully this will be of use.  And it's my first GH 'contribution', which is nice ;-)

**Comment by aria1th** [comment]
@Captain-Bacon Thank you for the issue! (you should make it as pull request to leave it as logged contribution, it will last forever :> )
I think I should add the more support for multiple paths / yaml file for path structure in future too.
